In [55]:
from __future__ import print_function
import numpy as np

In [2]:
p = 2
n = 10
mod = x^47 + x^5 + 1
# G = GF(p^n, name = 'x', modulus=mod)
G = GF(p^n, name = 'x')
print('Mame teleso:', G, 'a v nem modulo:', G.modulus())

Mame teleso: Finite Field in x of size 2^10 a v nem modulo: x^10 + x^6 + x^5 + x^3 + x^2 + x + 1


In [8]:
R.<x> = PolynomialRing(Integers(2))
s = []
# zde nastavime max polynomu
max_deg = 5
for i in R.polynomials(max_degree=max_deg):
    if i.is_irreducible():
        s.append(i)
        print(i)
print('Mame', len(s), 'ireducibilnich polynomu stupne max.', max_deg)

x
x + 1
x^2 + x + 1
x^3 + x + 1
x^3 + x^2 + 1
x^4 + x + 1
x^4 + x^3 + 1
x^4 + x^3 + x^2 + x + 1
x^5 + x^2 + 1
x^5 + x^3 + 1
x^5 + x^3 + x^2 + x + 1
x^5 + x^4 + x^2 + x + 1
x^5 + x^4 + x^3 + x + 1
x^5 + x^4 + x^3 + x^2 + 1
Mame 14 ireducibilnich polynomu stupne max. 5


In [4]:
h1 = G(x^45 + x^44 + x^43 + x^39 + x^38 + x^37 + x^34 + x^31 + x^28 + x^24 + x^20 + x^19 + x^12 + x^11 + x^8 + x^7 + x^2 + 1)
h2 = G(x^46 + x^45 + x^38 + x^31 + x^30 + x^29 + x^25 + x^24 + x^22 + x^18 + x^17 + x^14 + x^9 + x^7 + x)

In [5]:
# vybereme nahodne l
l = floor(random()*(p^n))
#spocteme g^l
print(G.gen()^l)

x^6 + x^4 + x + 1


In [6]:
G(0)

0

In [31]:
rozlozeni = []
for _ in range(1000):
    act = G(x)
    l = floor(random()*(p^n))
    mocniny = [0] * (len(s) + 1)
    mocniny[0] = l
    for i, pol in enumerate(s):
        r = floor(random()*n)
        mocniny[i+1] = r
        act = act * G(pol^r)
#         print act
        if act == G.gen()^l:
            rozlozeni.extend(mocniny)
            print(mocniny)
#             print(G.gen(), end='')
#             print('^', end='')
#             print(l, end='')
#             print(' =', end='')
#             for idx, mocnina in enumerate(mocniny[1:]):
#                 print(mocnina, end='')
#                 print('x', end='')
#                 print(idx+1, end='')
#                 print(' + ', end='')
#             print()
            
#         if act == h2*G.gen()^-l:
#             rozlozeni.append(mocniny)
#             print(h2, end='')
#             print('*', end='')
#             print(G.gen(), end='')
#             print('^-', end='')
#             print(l, end='')
#             print(' =', end='')
#             for idx, mocnina in enumerate(mocniny):
#                 print(mocnina, end='')
#                 print('x', end='')
#                 print(idx+1, end='')
#                 print(' + ', end='')
#             print()
            
            
print('Nasli jsme', len(rozlozeni), 'rovnic')
print(rozlozeni)

[393, 1, 9, 4, 4, 8, 1, 7, 0, 9, 5, 0, 0, 0, 0]
[401, 5, 3, 3, 1, 1, 1, 9, 0, 0, 0, 0, 0, 0, 0]
[401, 5, 3, 3, 1, 1, 1, 9, 0, 0, 0, 0, 0, 0, 0]
[474, 7, 0, 6, 9, 0, 4, 4, 9, 0, 0, 0, 0, 0, 0]
[630, 1, 0, 7, 3, 7, 3, 8, 0, 7, 9, 9, 0, 0, 0]
[953, 7, 8, 2, 9, 2, 9, 6, 1, 9, 0, 0, 0, 0, 0]
[736, 3, 6, 4, 3, 6, 7, 6, 3, 6, 6, 7, 7, 0, 0]
[66, 8, 9, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[821, 9, 0, 1, 1, 2, 5, 3, 3, 2, 2, 1, 0, 0, 0]
[428, 6, 9, 1, 1, 1, 6, 3, 3, 3, 2, 8, 7, 5, 4]
Nasli jsme 150 rovnic
[393, 1, 9, 4, 4, 8, 1, 7, 0, 9, 5, 0, 0, 0, 0, 401, 5, 3, 3, 1, 1, 1, 9, 0, 0, 0, 0, 0, 0, 0, 401, 5, 3, 3, 1, 1, 1, 9, 0, 0, 0, 0, 0, 0, 0, 474, 7, 0, 6, 9, 0, 4, 4, 9, 0, 0, 0, 0, 0, 0, 630, 1, 0, 7, 3, 7, 3, 8, 0, 7, 9, 9, 0, 0, 0, 953, 7, 8, 2, 9, 2, 9, 6, 1, 9, 0, 0, 0, 0, 0, 736, 3, 6, 4, 3, 6, 7, 6, 3, 6, 6, 7, 7, 0, 0, 66, 8, 9, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 821, 9, 0, 1, 1, 2, 5, 3, 3, 2, 2, 1, 0, 0, 0, 428, 6, 9, 1, 1, 1, 6, 3, 3, 3, 2, 8, 7, 5, 4]


In [32]:
def chunks(l, n):
    """Yield successive n-sized chunks from l."""
    for i in range(0, len(l), n):
        yield l[i:i + n]

In [33]:
for rovnice in chunks(rozlozeni, len(s)+1):
    print(rovnice)

[393, 1, 9, 4, 4, 8, 1, 7, 0, 9, 5, 0, 0, 0, 0]
[401, 5, 3, 3, 1, 1, 1, 9, 0, 0, 0, 0, 0, 0, 0]
[401, 5, 3, 3, 1, 1, 1, 9, 0, 0, 0, 0, 0, 0, 0]
[474, 7, 0, 6, 9, 0, 4, 4, 9, 0, 0, 0, 0, 0, 0]
[630, 1, 0, 7, 3, 7, 3, 8, 0, 7, 9, 9, 0, 0, 0]
[953, 7, 8, 2, 9, 2, 9, 6, 1, 9, 0, 0, 0, 0, 0]
[736, 3, 6, 4, 3, 6, 7, 6, 3, 6, 6, 7, 7, 0, 0]
[66, 8, 9, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[821, 9, 0, 1, 1, 2, 5, 3, 3, 2, 2, 1, 0, 0, 0]
[428, 6, 9, 1, 1, 1, 6, 3, 3, 3, 2, 8, 7, 5, 4]


In [23]:
for rovnice in rozlozeni:
    print(G.gen(), end='')
    print('^', end='')
    print(rovnice[0], end='')
    print(' =', end='')
    for idx, mocnina in enumerate(rovnice[1:]):
        print(mocnina, end='')
        print('x', end='')
        print(idx+1, end='')
        print(' + ', end='')
    print()

x^924 =8x1 + 1x2 + 2x3 + 8x4 + 2x5 + 1x6 + 4x7 + 6x8 + 9x9 + 9x10 + 7x11 + 7x12 + 1x13 + 2x14 + 
x^189 =4x1 + 3x2 + 8x3 + 4x4 + 4x5 + 1x6 + 5x7 + 1x8 + 2x9 + 0x10 + 0x11 + 7x12 + 1x13 + 0x14 + 
x^140 =7x1 + 4x2 + 8x3 + 1x4 + 7x5 + 7x6 + 2x7 + 1x8 + 6x9 + 4x10 + 4x11 + 3x12 + 4x13 + 4x14 + 
x^68 =0x1 + 8x2 + 1x3 + 8x4 + 5x5 + 7x6 + 0x7 + 3x8 + 8x9 + 5x10 + 7x11 + 2x12 + 7x13 + 2x14 + 
x^7 =6x1 + 0x2 + 5x3 + 8x4 + 4x5 + 4x6 + 5x7 + 2x8 + 9x9 + 0x10 + 9x11 + 6x12 + 5x13 + 1x14 + 
x^7 =6x1 + 0x2 + 5x3 + 8x4 + 4x5 + 4x6 + 5x7 + 2x8 + 9x9 + 0x10 + 9x11 + 6x12 + 5x13 + 1x14 + 
x^509 =5x1 + 3x2 + 5x3 + 0x4 + 5x5 + 6x6 + 8x7 + 8x8 + 7x9 + 6x10 + 0x11 + 1x12 + 0x13 + 9x14 + 
x^287 =0x1 + 0x2 + 6x3 + 5x4 + 1x5 + 3x6 + 5x7 + 7x8 + 7x9 + 4x10 + 7x11 + 7x12 + 9x13 + 4x14 + 
x^380 =7x1 + 5x2 + 5x3 + 7x4 + 9x5 + 5x6 + 5x7 + 7x8 + 6x9 + 0x10 + 6x11 + 5x12 + 1x13 + 9x14 + 
x^572 =5x1 + 5x2 + 8x3 + 2x4 + 3x5 + 9x6 + 1x7 + 3x8 + 1x9 + 3x10 + 5x11 + 2x12 + 3x13 + 8x14 + 
x^992 =7x1 + 0x2 + 3x3 + 1x4 + 8x5 

In [61]:
for rovnice in rozlozeni:
    print(rovnice[0], end='')
    print(' = ', end='')
    for idx, val in enumerate(rovnice[1:]):
        print(val, end='')
        print('x', end='')
        print(idx+1, end='')
        print(' + ', end='')
    print()

122 = 3x1 + 0x2 + 7x3 + 3x4 + 6x5 + 0x6 + 8x7 + 7x8 + 3x9 + 4x10 + 3x11 + 8x12 + 1x13 + 5x14 + 
563 = 4x1 + 9x2 + 9x3 + 8x4 + 6x5 + 8x6 + 9x7 + 0x8 + 1x9 + 9x10 + 1x11 + 5x12 + 2x13 + 6x14 + 
563 = 4x1 + 9x2 + 9x3 + 8x4 + 6x5 + 8x6 + 9x7 + 0x8 + 1x9 + 9x10 + 1x11 + 5x12 + 2x13 + 6x14 + 
236 = 7x1 + 5x2 + 1x3 + 7x4 + 3x5 + 7x6 + 9x7 + 3x8 + 5x9 + 5x10 + 9x11 + 5x12 + 0x13 + 5x14 + 
958 = 7x1 + 1x2 + 9x3 + 3x4 + 9x5 + 3x6 + 6x7 + 0x8 + 4x9 + 1x10 + 5x11 + 4x12 + 4x13 + 6x14 + 
651 = 3x1 + 8x2 + 2x3 + 1x4 + 4x5 + 4x6 + 0x7 + 1x8 + 2x9 + 2x10 + 3x11 + 4x12 + 6x13 + 4x14 + 
123 = 0x1 + 2x2 + 6x3 + 0x4 + 0x5 + 8x6 + 6x7 + 8x8 + 3x9 + 5x10 + 2x11 + 1x12 + 1x13 + 6x14 + 
559 = 9x1 + 7x2 + 3x3 + 5x4 + 9x5 + 1x6 + 9x7 + 7x8 + 7x9 + 9x10 + 8x11 + 8x12 + 0x13 + 6x14 + 
468 = 7x1 + 2x2 + 7x3 + 7x4 + 3x5 + 7x6 + 0x7 + 5x8 + 4x9 + 9x10 + 5x11 + 2x12 + 0x13 + 8x14 + 
882 = 8x1 + 1x2 + 9x3 + 2x4 + 5x5 + 7x6 + 7x7 + 7x8 + 4x9 + 8x10 + 6x11 + 7x12 + 2x13 + 8x14 + 
509 = 2x1 + 0x2 + 8x3 + 9x4 + 4x5 + 7x6 

In [48]:
prava_strana = []
matice = []
for rovnice in chunks(rozlozeni, len(s)+1):
    prava_strana.append(rovnice[0])
    matice.append(rovnice[1:])

In [57]:
A = np.array(matice)

In [58]:
B = Matrix(A)

In [60]:
W = vector(prava_strana)

In [66]:
X = B.solve_right(W)

In [69]:
B

[1 9 4 4 8 1 7 0 9 5 0 0 0 0]
[5 3 3 1 1 1 9 0 0 0 0 0 0 0]
[5 3 3 1 1 1 9 0 0 0 0 0 0 0]
[7 0 6 9 0 4 4 9 0 0 0 0 0 0]
[1 0 7 3 7 3 8 0 7 9 9 0 0 0]
[7 8 2 9 2 9 6 1 9 0 0 0 0 0]
[3 6 4 3 6 7 6 3 6 6 7 7 0 0]
[8 9 6 0 0 0 0 0 0 0 0 0 0 0]
[9 0 1 1 2 5 3 3 2 2 1 0 0 0]
[6 9 1 1 1 6 3 3 3 2 8 7 5 4]

In [ ]:
p

In [76]:
M = MatrixSpace(GF(p^n),len(s),len(prava_strana))
B = M(A)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [75]:
B.

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]